### ISSUE TITLE
Static IP and webserver password

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#103]
It is not possible to use static IP in the blueprint. 
Also opening opening the webserver asks for credentials which can not be configured (it seems)

**Comment by Blackymas** [comment]
sure it is possible - please have a look at

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup

3. Advanced configuration for all ESPHome and Home Assistant professionals


you have to copy the whole ESPhome code from the file nspanel_esphome.yaml and then make your changes.

But since this is advanced configuration, you should know this. 

I close the ticket because we do not support advanced configurations.
