### ISSUE TITLE
No additional menu on button hold for covers without position control / no stop button 4.0

### ISSUE THREAD

**Issue by geni0602** [Blackymas/NSPanel_HA_Blueprint#1063]
I have some covers in my house without position control. With 3.4.1 or older was possible to hold the cover button open the additional menu and use the up/down and stop button (s. screen) With 4.0 there is no action available by holding and I can only move the cover up by hitting  once or down if I press again. Stoping the cover is not possible. (up-down, or down-up)
The covers with positioning control are just fine. You can open the additional menu with press and hold and there is also a stop command always, if you use the button without holding. (up-stop-down, or down-stop-up)

Is it possible to somehow activate the stop command on those covers without positioning control?

![PXL_20230921_052252532~2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/4717eb7d-457a-4d24-bbde-73afd1d28ae6)

**Comment by edwardtfn** [comment]
I will take a look on how to have that thing back.
Basically, at this version those detailed screens are showing only the features available and for that one I didn't thought open and close are features also...
But you have a good point.

**Comment by geni0602** [comment]
Maybe it is possible to implement the same control as it is currently on covers with positioning control.
for example:
1st press - up 
2nd press - stop
3rd press - down

**Comment by edwardtfn** [comment]
The problem here is that we don't know the previous state. We currently send a toggle call and leave to Home Assistant to decide what to do. I can look for current state and if it is "opening" or "closing", send a "stop" call instead, however for the next call I don't have that info if it was closing or opening before, so my only option is to send a "toggle" and leave for HA to decide again, but I bet it will keep closing unless it is closed, as fo HA 1% open is "opened" state.

**Comment by edwardtfn** [comment]
If you can help testing I can create a testing version for this.

**Comment by edwardtfn** [comment]
It is on `dev` now. You will have to update the Blueprint to try it. No need to update ESPHome and TFT for this test.

**Comment by geni0602** [comment]
Thanks. Looks good now.
