### ISSUE TITLE
Why can't the Blueprint be installed on HA ver.2022.10?

### ISSUE THREAD

**Issue by softhuntermike** [Blackymas/NSPanel_HA_Blueprint#114]
My HA installation always had issues with 2022.11 and 2022.12, it keeps rebooting automatically every 15-30 mins. So now I'm still running 2022.10.5, while installing the blueprint always asked for 2022.11/2022.12. Anyway to add the blueprint on 2022.10.5? Thanks

**Comment by Blackymas** [comment]
we have installed this because we have done most of the programming from this version and are not sure and have not checked if it is all ok with an older version.

But you can delete the whole thing.

Open in HA your editor and search the blueprint file.

```
  homeassistant:
    min_version: 2022.11.1
```

At the top under the general description is the following.

Delete the two lines and restart HA or the service automations - after that it also works with an older version.

![Bildschirmfoto 2022-12-19 um 08 52 23](https://user-images.githubusercontent.com/41958506/208375025-838c08e0-a409-48c6-bb23-10b2df6c26d4.png)

**Comment by Blackymas** [comment]
I close the ticket
