### ISSUE TITLE
Unable to update ESPHome

### ISSUE THREAD

**Issue by fzambroni** [Blackymas/NSPanel_HA_Blueprint#1212]
Greetings,

Since the recent ESPHome update on October 5, 2023, I've encountered an issue updating my two NSPanel devices. Please refer to the attached file. Is there any connection between this problem and the NSPanel_HA_Blueprint project?

[logs_nsoffice_run (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13230362/logs_nsoffice_run.1.txt)

**Comment by edwardtfn** [comment]
> xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
> compilation terminated.

Looks like your compiler is crashing.
If you are using ESPHome as an add-on to your Home Assistant, please take a look at the memory consumption when compiling this. This won't be a surprise if you are using like a RPi3 with only 1GB of RAM, but if you have more RAM then it is probably something else.

If that is the case, adding this to your yaml may help:
```yaml
# Limit the amount of resources used for compiling
esphome:
  compile_process_limit: 1
```
This is from our customization docs: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#compiling-esphome-on-lower-powered-machines

Also, restarting the host system or stopping some other add-ons in your Home Assistant could help freeing some memory for ESPHome.

> Please refer to the attached file. Is there any connection between this problem and the NSPanel_HA_Blueprint project?

Well, this project is quite complex (in terms of different components used) when compared to an average ESPHome project, so you will have more chances to reach the limits first here.
There's no conflict between this project and ESPHome v2023.10.5. This is probably breaking due to the ESPHome might be requiring more memory from a system that probably was already close to the limit.

**Comment by fzambroni** [comment]
Thank you for your explanation. I attempted various approaches, but all of them were unsuccessful. I am using a Home Assistant Yellow server with only 2 GB of RAM. Ultimately, I resolved the issue by reverting to my previous HA RPi4 server.
