### ISSUE TITLE
TFT Update File doesn't do anything

### ISSUE THREAD

**Issue by Stino014** [Blackymas/NSPanel_HA_Blueprint#1216]
Hello,

Today i succesfully flashed a nspanel to HA.
The nspanel works from HA (ssid is visible, relays can be toggled from the UI etc)

For the tft file i create a folder under config named www, i put the file from github inside this folder.

When i push on update file nothing happens, when ik test the url from the file http://url:port/local/nspanel_eu.tft the file downloaded local on my system.

What is my problem?
(its my first display so i'm noob)-

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/91420601/6716a63c-31fa-41d2-a00e-4f8a410c7b48)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/91420601/e3cea61c-2bb7-41b3-a503-85a0fd64a50e)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/91420601/5eb3121d-3966-4a78-b303-3540dc9fcae9)

**Comment by geni0602** [comment]
Check here last point 9
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

**Comment by edwardtfn** [comment]
@Stino014, I would appreciate if you could give a try in the new Upload TFT engine we are testing in `dev`. It is more robust and it captures more logs.

In order to try that, please do the following:
1. On your yaml, in the `remote_package` area, change from `ref: main` to `ref: dev`. You can leave everything else as it is.
2. Install the new settings in your device. It's fine if you install wirelessly.
3. Try to use the "Upload TFT" button again, but this time, please capture the logs from ESPHome.
4. Change it back to `ref: main`
5. Flash your device again (wirelessly is OK).

**Comment by Stino014** [comment]
> Check here last point 9 https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

This worked for me 😁
