### ISSUE TITLE
References to non-existing entities

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#127]
There are references to unknown entities ids in the Blueprint. It should be using references to the input variables instead:

| Entity ID | State | Location |
| ---- | :---: | ----- |
| input_boolean.trigger_nspanel_boot | missing | blueprints/automation/Blackymas/nspanel_blueprint.yaml: 1336  |
| climate.hotwater_temp | missing | blueprints/automation/Blackymas/nspanel_blueprint.yaml: 2992, 4272 |
| climate.outdoor_temp | missing | blueprints/automation/Blackymas/nspanel_blueprint.yaml: 3011, 3027 |

**Comment by Blackymas** [comment]
thanks we will check

**Comment by deejaybeam** [comment]
Hi
the input_boolean.trigger_nspanel_boot is an "internal" developing helper. To not confuse normal users, it is not exposed as an input, and if it is not created in HA it could never trigger a action, but because it is an input_boolean, it can be created as an helper on any HA-instance if needed.
The other two components are full-names of variables inside the tft: climate page (local) variable of hotwater (if you are currently on the climate page, same for the outdoor_temp
They have nothing to do with HA-Entities

**Comment by edwardtfn** [comment]
Great!
Thanks for clarifying.
