### ISSUE TITLE
Show Status of Entities / sensors

### ISSUE THREAD

**Issue by xiaoandy80** [Blackymas/NSPanel_HA_Blueprint#128]
Hello, I'm missing the function to have a button(entity for example garbage), and then by long pressing, I will see a list of values like days until it will be emptied.
Another example is to see my 3D Printer Status and how much Progress it has Temp values of the Hotbed or Nozzle.

I have all that values but they are not shown if I want to choose.

From my understanding, at the moment it is only possible to control stuff but not to show the status of anything.

ps: not sure why but pressing on the weather icon will lead to a blank screen do I have to configure anything to get details?

Thanks for the great work.

**Comment by w00ter** [comment]
I'm sure this is something the (awesome) team have planned; currently the buttons are limited to entities Cover, Light, Switch and Input Boolean. Would be cool to either have buttons or screens that are able to show entitie/sensor data. 

ps. yeah, the Weather icon also shows a blank/empty screen for me too

**Comment by Blackymas** [comment]
> Hello, I'm missing the function to have a button(entity for example garbage), and then by long pressing, I will see a list of values like days until it will be emptied. Another example is to see my 3D Printer Status and how much Progress it has Temp values of the Hotbed or Nozzle.
> 
> I have all that values but they are not shown if I want to choose.
> 
> From my understanding, at the moment it is only possible to control stuff but not to show the status of anything.
> 
> ps: not sure why but pressing on the weather icon will lead to a blank screen do I have to configure anything to get details?
> 
> Thanks for the great work.

hi garbage is in the roadmap - i would like to have it too ;)

We also plan new switch bottles on the start screen that we can then use for other things. Until now the focus was on the control of devices 

Here is an example how it could look like

![Home Page](https://user-images.githubusercontent.com/41958506/210022847-30f23af9-65c6-40dd-8a57-6df81c6ae97f.png)

But it will take a moment because we are only two and also have family :)


For the Weather Default problem we have already found the issue.

When HA is reinstalled the Weather Default service is now called weather.forcast_home

But you can simply rename the integration in HA to weather.home and then it will work again.

![Bildschirmfoto 2022-12-30 um 01 15 36](https://user-images.githubusercontent.com/41958506/210022991-7cff5c93-4571-4812-9273-159903a644bc.png)

**Comment by Blackymas** [comment]
I close the ticket
