### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#1283]
1st Thank you for this great update! I like the option with bigger chips on homescreen and TFT upload.

I noticed that all the notifications are not working anymore.
Would be nice to get a fix for that!

BR

Markus

**Comment by edwardtfn** [comment]
I'm not at home for the coming few days, so I cannot duplicate this... But could you please give more details?
When you call the notification show service nothing is shown in the panel?

**Comment by edwardtfn** [comment]
Can you see any error message either on ESPHome or Home Assistant (Settings > System > Logs)?

**Comment by MarkuZP** [comment]
See messages from my different automations (waste collection, Dishwasher, mailbox) are not shown anymore. When I try to start thema manually this error message is shown:
Fehler beim Ausführen einer Aktion
extra keys not allowed @ data['text']. Got None required key not provided @ data['message']. Got None

I think there are some special characters that are not allowed anymore... !?

**Comment by MarkuZP** [comment]
<img width="1057" alt="Bildschirmfoto 2023-11-16 um 10 03 08" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109298227/6b5a7143-1196-4ad5-aab6-38cc7781647e">

**Comment by MarkuZP** [comment]
Okay I made the notification new with exact same text an signs. Now its working! Strange!

**Comment by edwardtfn** [comment]
ESPHome 2023.11 includes a new "Text" component, so that word ("text") became a reserved one and cannot be used as parameter for services anymore. That was the main reason we released v4.1 now (I was planning to do after coming back from my road trip in North Sweden ❄️😉) to anticipate our code failing compiling with the new ESPHome.

So, we changed that parameter from "text" to "message" and this was probably the reason you got that error.

If you have external call to that service, you have to update your call to the new parameter (all the format is the same, it's just about rename the parameter).

**Comment by deejaybeam** [comment]
It makes always sense to read the releasenotes (https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/ReleaseNotes.md)
```Service notification_show parameter text was renamed to message to support ESPHome 2023.11.0.```

Looks like the re-creation of your notifications exchanged paramter text to message

**Comment by MarkuZP** [comment]
thank you!
