### ISSUE TITLE
Configuration and Synchronization Issue with NSPanel via Blueprint after update to 4.1

### ISSUE THREAD

**Issue by Jurrjuna** [Blackymas/NSPanel_HA_Blueprint#1285]
Subject: Configuration and Synchronization Issue with NSPanel via Blueprint

### Issue Description

The NSPanel functions correctly after the recent update. However it is not possible to change configuration with the new 4.1 blueprint. When attempting to configure and synchronize NSPanel using Blueprint, the existing settings are not being loaded into the Blueprint. Although the panel can be selected, the settings do not update as expected. The issue is observed even though the Panel, TFT, ESPHome, and Blueprint versions are all at 4.1. 

### Steps to Reproduce

1. Open Blueprint in HA 
2. Navigate to the NSPanel configuration section.
3. Select the NSPanel.
4. Observe that existing settings are not loaded in the Blueprint.

### Expected Behavior

The Blueprint should reflect the existing settings of the selected NSPanel.

### Current Behavior

The Blueprint does not update with the existing settings of the NSPanel.

### Additional Information

- TFT Version: 4.1
- ESPHome Version: 4.1
- Blueprint Version: 4.1

![4 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/24192343/876fb12e-9602-4177-90db-248e2ca5c81d)

### Steps Taken So Far

- Reviewed Blueprint configuration.
- Checked synchronization process in the code.

### Additional Notes
This marks my inaugural attempt at submitting an issue. I made a diligent effort to check if a similar issue had been raised previously, but I acknowledge the possibility of oversight. I apologize if there is an existing issue that mirrors my findings.

I have encountered difficulty understanding the underlying mechanics of the NSPanel configuration. I am uncertain about where the panel configuration is stored and how it is retrieved during the Blueprint synchronization process. Specifically, I would like clarification on whether the configuration is read directly from the NSPanel or if it is stored in another location.
This lack of clarity about the configuration retrieval mechanism makes it challenging to pinpoint the source of the synchronization issue. Any insights into where and how the panel configuration is managed would be greatly appreciated, as it would assist in troubleshooting and resolving the problem effectively.

**Comment by edwardtfn** [comment]
Thanks a lot for the detailed information. Makes me think about ~~stole~~ get inspired by your report and use something like this as a template for helping people when reporting issues.

But about your question, we wanna make the panel as autonomous as possible (be able to work even when HA or Wi-Fi isn't available) at the same time it should be easy for anyone be able to use without the need of coding experience. Obviously this is not always possible, as you will se we indicating some coding here, but we try to do this only when is a very specific request that might not make sense for all others.

With that said, you will find only a couple of settings on the ESPHome yaml (the link to TFT and the relay used for climate, apart of wifi settings), a few are on the device's page on HA (a Restart button, sleep time, etc), but all the page settings (how it should look, the content of pages, etc).

Most of the page construction, when depending on data from HA, have all the engine on the Blueprint side, which reads the settings at each execution (which happens on every button pressed).
Everything that can run from the panel (let's say, time display), receives the info from HA with various services (we cannot squeeze everything in a single service due to ESPHome native API limitations) is transferred based on some triggers (HA starting, the panel boot or reloading automations, which also triggers when you press the button "Save" in the automation).

So, if you are seen the Home page and change setting like the size of chips or language, the new settings will be visible in the screen without need to refresh. It will take a few seconds (something we implemented recently to distribute the load on system with large number of panel's).
However, pages that are basically created from Home Assistant (blueprint) side, aren't refreshed with HA automation reload. The only trigger for that is the page loading.
Is that an issue for your use case?

I woukd love to hear more and understand better your cases. Refreshing a page with change in settings will probably be half dozen lines of code only, but as that was never asked, we never thought about this. 😉
