### ISSUE TITLE
Incorrect Time Display on NSPanel with Firmware Version 4.1.1

### ISSUE THREAD

**Issue by n1kDon** [Blackymas/NSPanel_HA_Blueprint#1300]
**Issue Description:**
I have three NSPanel displays running different versions of the firmware. Two of them are on version 3.4, and one is on the latest version 4.1.1. I've noticed that the NSPanel running firmware 4.1.1 is displaying the time incorrectly—it's one hour early compared to the correct time and compared to the other two panels running the older firmware version. All are manged with the same homeassistant running on docker with different blueprint versions selected.

**Troubleshooting Steps Taken:**
Checked and confirmed that the time zone settings are correct in ha.
Restarted the NSPanel and ha.

**Firmware Version: 4.1.1
Time Zone: Berlin (GMT+1)**

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#enforce-time-zone

**Comment by edwardtfn** [comment]
> but after a reboot, the time is lost again and the ESPHome firmware is rolled back to 4.1 :( 

This looks like some other issue... Could you please share your ESPHome yaml? Please remove any sensitive info before sharing.

**Comment by edwardtfn** [comment]
@Anzic23, in your case I believe the issue is related to the use of the advanced package. It includes framework esp-idf, however for the change of framework it's recommended to flash via serial/usb otherwise you can have partitioning issues and your panel could boot in an older firmware (with older settings).

Please try adding this to your yaml:
```yaml
esp32:
  framework:
    type: arduino
```

This will force it to arduino. If you have plans to flash it by serial/usb, then remove those lines before.
`esp-idf` have a better memory management than `arduino`, but changing those requires flash via usb/serial.

**Comment by Anzic23** [comment]
@edwardtfn Thank you! Adding the code to the config helped!

**Comment by edwardtfn** [comment]
@n1kDon, are you still facing this issue or should we close this?

**Comment by n1kDon** [comment]
thats funny, I uploaded the change in the yaml 10 minutes ago, now the time is correct, thanks!
