### ISSUE TITLE
Initial TFT update failure, now getting data error

### ISSUE THREAD

**Issue by ecrode** [Blackymas/NSPanel_HA_Blueprint#1312]
Flashed to main initially and tried to update the tft image. Once the command was issued, I saw the progress on the display, but it was stuck at 0 for the longest time. Alas I didn't have logs enabled, or at least could not access them wirelessly, and eneded up rebooting the unit during the firmware upgrade to enable logging.
From than on I now see "System Data ERROR!" on the display.
I've followed the similar issue, and changed the ref: to dev. Uploaded that and tried the flash again, here are the logs:

[errorlog.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13418988/errorlog.txt)

Is the display bricked? Is there an original sonoff image somewhere I could use to reset everything to factory defaults and try again?

**Comment by edwardtfn** [comment]
> Is the display bricked?

I don't think so. Those error messages sounds quite critical sometimes, but usually a restart or a new TFT transfer solves everything. 😉


> Is there an original sonoff image somewhere I could use to reset everything to factory defaults and try again?

I'm in the road now, so I can't go deep on this, but if you search on the issues in this repo you will find a couple with instructions to recover the original firmware.
However, o don't think this will help you. The problem is most likely related to the fact you are using https. This client from ESP works much better and faster with http (without security), so if you have a http server available (Home Assistant?) you should try that.

Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#2-http-instead-of-https

**Comment by ecrode** [comment]
Thank you,
I have been trying to troubleshoot the issue further after the initial ticket creation, and switching to http was one of the steps. File is hosted on home assistant (supervised) and the current URL uploaded into the image is "http://debian.this:8123/local/nspanel_us.tft". Logs indicate that full image seems to be quickly pulled down, but otherwise show the same failure / attempts.
The issue may be me getting unlucky and damaging the ribbon connector somehow during the initial programming steps. Not sure why I could not connect to the unit and check the logs when it initially has stuck on 0% as now I see that "logging" is not needed to have logs available wirelessly via  esphome.

**Comment by edwardtfn** [comment]
From your logs I see the system trying to recover the `Nextion is not connected!` by sending an `Exit reparse` command, which is usually enough when your display still having the original Sonoff TFT, which I believe it is your case.
```log
[15:07:20][W][nextion:077]: Nextion is not connected! 
[15:07:20][D][main:2485]: Exit reparse
[15:07:21][W][nextion:077]: Nextion is not connected! 
```
After that, the system will try other ways to overcome that situation, but I see you pressed the "Upload TFT" before that finished (unfortunately we have no control to be able to disable that button until the system finished it's boot sequence).

So, I would suggest first you just wait a bit more after a boot before trying to Upload TFT. In a minute or two you will see the message about boot sequence finishing in your log, so after that you can press that button.

If that still not fixed, I would ask you to share your ESPHome yaml here (please hide sensitive info) so we can propose some changes.

I think is very unlikely this is an issue with the ribbon connector. These displays are quite challenging due to the Reparse protocol used by Sonoff. Once you get rid of that, it should be a bit easier.

**Comment by ecrode** [comment]
I have tried to keep it plugged in and trying to recover for a while. I've gotten a replacement display and everything worked with same setup, though I did have to specify esp-idf framework, otherwise I was getting the template mismatch error. Closing this issue as likely hardware related.
