### ISSUE TITLE
xtensa-esp32-elf-g++: fatal error

### ISSUE THREAD

**Issue by Dunkhase** [Blackymas/NSPanel_HA_Blueprint#1344]
Hi when i validate the Firmware for the upload, it works fine.
when i compile it than i receive the following Error, i hope some body can help me.
Regards 
Holger
```log
INFO ESPHome 2023.11.4
INFO Reading configuration /config/esphome/nswohnzimmer.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nswohnzimmer (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling .pioenvs/nswohnzimmer/src/esphome/components/adc/adc_sensor.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/nswohnzimmer/src/esphome/components/api/subscribe_state.cpp.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [.pioenvs/nswohnzimmer/src/esphome/components/api/api_pb2.cpp.o] Error 1
========================= [FAILED] Took 33.27 seconds =========================
```

**Comment by edwardtfn** [comment]
Your compiler is crashing... Try to limit resources using this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#compiling-esphome-on-lower-powered-machines

**Comment by eavyon** [comment]
Just had the same. And even I limited the process it crashed a few times before finally finishing it. For now just retry a few times. System has 4GB total but I guess the container is still limited.

**Comment by Dunkhase** [comment]
Thanks a lot for the Help, i will try today and give Feedback.

**Comment by IJsbeer-NL** [comment]
See:
https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines

"Running ESPHome on lower powered machines[¶](https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines)
People have noticed that trying to compile their projects on machine such as the Raspberry Pi 3 would crash either the whole machine or the ESPHome add-on, or Home Assistant. This is due to having less RAM and CPU power available to run all of the things at the same time. A new config option has been added as per the example below that should help to allow compiling on machines such as Raspberry Pi 3. By default ESPHome tries to compile using all of the processor cores, and this allows you to limit it to a lower amount.
"


Can this be a configuralble option to turn this on  ?



esphome:
  ...
  compile_process_limit: 1

**Comment by edwardtfn** [comment]
Yes, you can add this as a customization to your yaml file.

More details here:
- https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#instructions
- https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#compiling-esphome-on-lower-powered-machines

**Comment by andythomas** [comment]
My compilation does not crash, but it is painfully slow, because I am running Home Assistant on a Synology NAS with a Celeron processor. It might be obvious to you, but I was excited to learn, that the compiler can also be [installed](https://esphome.io/guides/installing_esphome) on a different computer as a stand alone version. Then, you can, e.g., `esphome compile livingroompanel.yaml` and generate the `.bin` file. Please note that there are two `.bin` files generated and you need the `...-factory.bin` one. Subsequently, you can upload this file via USB or OTA.  

The installation even comes with its own dashboard and a local webserver and I added all panels and bluetooth proxies to both dashboards, the build-in and the newly installed one. This cuts my compile time from 15min (NAS) to 43s (M1 Mac), which makes any kind of tests so much less painful :)

Maybe, this is an option for you as well.

**Comment by edwardtfn** [comment]
I use ESPHome on my laptop also and it works fine (and fast).
Anyways, I'm planning to add a "pre-built" version in the near future. That means a pre-compiled `.bin` file to be published in the repo, so you could download that and install in your device, without the pain of compiling locally. The downside is that your will be limited to what is set there, not able to customize it.
But this is future. 😃

**Comment by edwardtfn** [comment]
@Dunkhase, any update to this?

Maybe this can be helpful:
- #1636

**Comment by Dunkhase** [comment]
Hi, sorry you can close it. After stopping all the Services on the Homeassistant Yellow, I can compile it.
Kind regards
Holger

Von: Edward Firmo ***@***.***>
Gesendet: Dienstag, 16. Januar 2024 13:56
An: Blackymas/NSPanel_HA_Blueprint ***@***.***>
Cc: ***@***.***; Mention ***@***.***>
Betreff: Re: [Blackymas/NSPanel_HA_Blueprint] xtensa-esp32-elf-g++: fatal error (Issue #1344)


Hey @Dunkhase<https://github.com/Dunkhase>, are you still facing this or should we close this issue?

**Comment by IJsbeer-NL** [comment]
After updating to the latest ESPHome, I still encounter this issue. I will see If I can find another device to compile. STOPPING all additional services does not free up enough memory.

**Comment by edwardtfn** [comment]
Could you please report it in another issue so we can track it better?

**Comment by nosuntoday** [comment]
Had the same problem today on my Home Assistant Blue / Hardkernel ODROID-N2/N2+. Stopping other services solved it. Especially Frigate is resource hungry it seems
