### ISSUE TITLE
TFT Update won't work because of https?

### ISSUE THREAD

**Issue by root2k** [Blackymas/NSPanel_HA_Blueprint#1384]
Hey guys, I'm nearly giving up to update my nspanels ...
The first problem was to establish an connection to the panels with my usb2serial adapter. But maybe was my fault maybe the pins were not fitted well to the board, but then it worked.

But the problem I have is that the tft file won't be transferred to the panels. The first one (which had the blackymas already installed) just restarts after push the tft file upload button. And then it just shows me the empty pages and the background, but only the text "loading".

The 2nd nspanel is restarting too but shows me still the sonoff screen.

The last time i did the update there was a black screen shown on the panels and a loading bar with percantge.
But this time not, just restarting.

Maybe is it a problem that I set up https connection to home assistant?
In the yaml file of the nspanels I have written the url just with http://... not https.

Hopefully someone can help me out.

**Comment by edwardtfn** [comment]
Could you please share the yaml used for ESPHome of one of those panels where you couldn't update the TFT? Please remove any sensitive information before sharing.

**Comment by plasterer41** [comment]
Funny I tried to update mine this morning and same thing happened. I then changed the yaml to download the tft file from GitHub instead of locally and it worked on all 4 of my panels. I am using the main (not dev or beta)Sent from my iPhoneOn 5 Dec 2023, at 07:40, root2k ***@***.***> wrote:﻿
Hey guys, I'm nearly giving up to update my nspanels ...
The first problem was to establish an connection to the panels with my usb2serial adapter. But maybe was my fault maybe the pins were not fitted well to the board, but then it worked.
But the problem I have is that the tft file won't be transferred to the panels. The first one (which had the blackymas already installed) just restarts after push the tft file upload button. And then it just shows me the empty pages and the background, but only the text "loading".
The 2nd nspanel is restarting too but shows me still the sonoff screen.
The last time i did the update there was a black screen shown on the panels and a loading bar with percantge.
But this time not, just restarting.
Maybe is it a problem that I set up https connection to home assistant?
In the yaml file of the nspanels I have written the url just with http://... not https.
Hopefully someone can help me out.

**Comment by edwardtfn** [comment]
> In the yaml file of the nspanels I have written the url just with http://... not https.

Avoid using httpS, and avoid using url pointing directly to GitHub.
And please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

**Comment by edwardtfn** [comment]
v4.1.4 (to be released very soon) will introduce some small changes that might help with the TFT upload process, so could you please try to update your system when that is released and then try it again.

And it's always good to take a look at the link I've sent a few minutes ago.

**Comment by edwardtfn** [comment]
v4.1.4 was just released.
Please update your system and try it again.
If the issue persists, please reopen it.

**Comment by root2k** [comment]
Short info: tried yesterday the way plasterer41 mentioned and it worked very well.
So I guess that might be occured because of https.
@ edwardtfn: I try to update it again this evening by local update to version 4.1.4.
I willl give another info afterwards.
