### ISSUE TITLE
feature request: change hardware button label dynamically

### ISSUE THREAD

**Issue by aep** [Blackymas/NSPanel_HA_Blueprint#1409]
i'm using the hardware button to change an input_select to cycle through scenes.
would be great if the hardware button label would reflect the current scene.

**Comment by edwardtfn** [comment]
So, on the current version, you can change those by calling the service `esphome.xxxxx_send_command_text_printf` like this:

```yaml
service: esphome.xxxxx_send_command_text_printf
data:
  component: home.right_bt_text
  message: New label
```
* Change to `component: home.left_bt_text` for the left button.

However, this will be reloaded every time the page Home is opened, so you will have to add that call to an automation based on the current page sensor having `home` as it's value (and probably a small delay to make sure you don't update this before it is update by the blueprint, otherwise it will be replaced).

I've changed on v4.2 to update only when the panel reloads, which happens when the panel shows the boot page (usually due to a restart) or when the automation is reloaded (due to some change, a full automations reload or HA restarting).
With that, it will be quite feasible to you to change it as you want with the service calls.

**Comment by edwardtfn** [comment]
- #1556
