### ISSUE TITLE
Feature Request: Light on/off toggle on light entity page

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1549]
Considering that we now can add more custom buttons to the home page, and the action by pressing them brings up an entity page in the case of an RGB/Dimmable light... it would be nice to be able to turn on/off the light by a button... instead of having to dim down to 0%.

Same goes for other entity types where applicable eg. covers. Fan already has on/off on the page.

**Comment by crls00** [comment]
This does not seem to be a feature request but a bug. When I add any lights controlled by ON/OFF switches to the custom buttons in the home page I don't expect to get a slider, however I always get one regardless of the light. 

The same light entities in the home assistant interface only return an on/off button because they are not even dimmable. I would expect the custom buttons to behave the same, even if the light had a dimmer option, I would assume this tiny icons are expected to provide a shortcut to turn things on/off quickly... with switches it works just fine.

**Comment by Doughboy68** [comment]
I think there was a reason for that (maybe was alarm page, can't remember) but I agree that they should work like regular buttons and a long press displays the screen.
I still would like an on/off toggle on that screen though.

**Comment by edwardtfn** [comment]
Done!
It is in `dev` now, but it will be part of v4.3 to be released soon.
