### ISSUE TITLE
Change the inside temperature identity

### ISSUE THREAD

**Issue by kalagan55** [Blackymas/NSPanel_HA_Blueprint#159]
Possibility to replace the identity of the temperature inside the NSPANEL probe (not always correct) by another entity (other probe, netatmo, sonoff...)

**Comment by Blackymas** [comment]
Hi,
is not possible at the moment but is on the roadmap.

Just have a look at the other issues where there is already such a topic.

I don't know why this is necessary - we have built in a temperature correction for the NSPanel - so you can adjust the NSPAN temp sensor exactly.

I have the display in 6 rooms and bia temperature correction set this sensors and after that runs perfectly ;)

![Bildschirmfoto 2023-01-04 um 23 02 04](https://user-images.githubusercontent.com/41958506/210658302-46911984-0331-4708-bedf-7bf0e7a17990.png)

I am closing the ticket because there is already a ticket. But try the temeprature correction you will be impressed ;)

**Comment by kalagan55** [comment]
Thanks

**Comment by Blackymas** [comment]
hi - add Indoor Temp Sensor

See here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
