### ISSUE TITLE
Entity icon is overlapping part of the entity value

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#1621]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

Entity icon is overlapping part of the entity value

### Steps to Reproduce

Configure entity in `Sensor 03 - ENTITY` with a value of more than 9 characters

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/7eb13c96-7dd7-4264-aebd-5f236097e52b)

**Comment by hapklaar** [comment]
Also happens when showing a string `Zeer mooi` I see in a pic I made earlier
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/d14b2f4f-d2e3-4387-a453-e73e4eb43b6e)

**Comment by edwardtfn** [comment]
Hey, this is due to the limited space assigned to that value field and this haven't changed since a while.
Unfortunately the way this Nextion display works requires defining the exact size for each component. All the components in this project have a limit on it's size and this is since the beginning.
