### ISSUE TITLE
Use icon defined in entity

### ISSUE THREAD

**Issue by jbernadina** [Blackymas/NSPanel_HA_Blueprint#165]
When an entity (e.g. script) is chosen for a button, it would be great a great option to choose for the icon defined in the entity is used for the button.

**Comment by tikismoke** [comment]
This mean the hmi files must handle all ha icon.
@Blackymas is it even possible?

**Comment by Blackymas** [comment]
hi,

possible but for 2 reasons not implemented or difficult to implement

1. all icons would have to be stored in HMI Nextion Editor and then be selectable in the blueprint.

2. the use of so many icons eats the small memory of the NSPanel - also would have to be created in the button another field or many large buttons.

Something like this can be done at the end of the project or when the main functions are all in, because then we see if there is memory left or not.

**Comment by X-Ryl669** [comment]
In lovelace, they've used a font to store the icons, so it doesn't use that previous bitmap memory part. Maybe it's possible to do so here too ? 

That implies however that icons are monochrome (Nextion can't draw color font anyway).

**Comment by Blackymas** [comment]
> In lovelace, they've used a font to store the icons, so it doesn't use that previous bitmap memory part. Maybe it's possible to do so here too ?
> 
> That implies however that icons are monochrome (Nextion can't draw color font anyway).

Do you have a link to the doku and I will have a look at it?

**Comment by X-Ryl669** [comment]
[Here](https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker---Basisinstallation#8--icon-typescript-anlegen), click on the cheatsheet for the list of icons that's possible to use. These are in a font that contains all those icons, you just need to use the right unicode char to get the icon.

**Comment by danwright87** [comment]
Just be aware the fonts a quite large in nextion, I'm using this method currently, mdi iconds + standard ascii sizes are:
font size 24 - 1.24M
font size 32- 1.57M
font size 48 - 1.75M
font size 80 - 3.17M

If you can get aware with just 1, maybe 2 sizes looks like its should just be manageable.

**Comment by Blackymas** [comment]
> 

I have already noticed that it becomes very large. You would then probably have to agree on only 1-2 sizes.

Currently I have not really understood how it works I could only successfully rebuild it.

@danwright87 @X-Ryl669 - Maybe you could also connect on Discord and discuss the topic

**Comment by X-Ryl669** [comment]
## How it works
In a usual GUI, when you have an icon, you'd use a transparent image file format (like PNG or SVG) and let the system draw the transparent image on your background.

However, in Nextion Discovery, you can't do that, since it doesn't support transparent image format. So you have to pin/lock the image at some predefined position over a pre-defined image background and perform as many render of the bounding box of the icon (one when the icon is idle, one when it's active, etc...) and save these images in Nextion's flash.

### The trick:
When using font's icon (that is, a font that's contains icons as glyph for some unicode's index), you're not dealing with shitty Nextion image code, but with the less shitty Nextion's font code. 

When using a font, Nextion Editor render the glyph as binary bitmap (0/1 to say if the pixel is on or not on the grid). 
And when drawing a text, Nextion's display will blit a pixel of the given font color where the bitmap is 1 (and **skip** when it's 0). This gives a dummy pseudo transparency (a bit like GIF), where the background is visible where the text is not.

Typically, this means that:
1. You have a lot less graphic work to do, because you don't need to place your icons and perform 2 renders (or more) for each icon's color, position, size, background. It's done at runtime by Nextion's firmware.
2. But you're limited by the font's rendered bitmap size and Nextion's memory
3. You can only use the icons that are in the font. 
4. You must remember which unicode index is used for each icon (in lovelace, I thing it's a kind of a standard, you can probably extract it from HA's frontend)
5. You don't have anti-aliasing for fonts.

So in the end, if using such font with icons, you'd keep a limited amount of font size to limit the number of rendered bitmap's font. It's not rendered in runtime by the display (it's too dumb for that), it's only blit. You'll likely want to only store the usual font size (32px ? 24px ? I don't remember) and *maybe* a large version (64px ? 80px ?) for the home screen.

**Comment by Blackymas** [comment]
would be built in version 3.1.0 for the entity page.

We will extend the feature to more pages step by step.
