### ISSUE TITLE
Update tft took 22 hours then went to a white screen error loop

### ISSUE THREAD

**Issue by iamandymcinnes** [Blackymas/NSPanel_HA_Blueprint#169]
Update tft took nearly a whole day, then when it completed it had a white screen that kept cycling through saying:

Check data... 100%
Update Failed:check Error!

I rebooted, it then says:

System Data ERROR!

So I tried to do the upload again, it's still going slow as heck but now the progress screen is in the wrong orientation (mine is the EU version). 

This is the first thing I've flashed on to it as I only just got it so didn't think I needed the blank tft option. Although I was just going to try that as this is looking the same as before but the instructions don't make sense. I've uploaded the blank tft to my www directory, but then it mentions finding the update tft service, and then talks about updating the url to point to the path of the blank tft, but there is no url property, even in the yaml editor on the developer tools:

![image](https://user-images.githubusercontent.com/47521626/211398809-eb7e9342-653a-4ad7-940e-c2bbd271b696.png)

I also notice a lot of people talking about the baud rate, it defaults to 115200, but there seems a lot of talk about 9600? What should it be and I take it to edit it I copy the contents of the esphome yaml, and edit accordingly rather than using the reference?

Many thanks

Andy

**Comment by iamandymcinnes** [comment]
I've managed to blank the screen off now, but when I go back to the quick start and flash the vanilla esphome then trigger the upload tft from the integration page, the screen flickers once and I hear the 2 beeps of the nspanel restarting, but it doesn't seem to update the screen.

**Comment by iamandymcinnes** [comment]
I think the tft is probably too big to upload over https, the poor little esp32 is probably running flatout trying to handle that. It might be better to tell people to upload the tft to www and use your homeassistant ip on http in the config like you do to upload the blank file.

It's not finished yet, but it's over 40% in 2 minutes now whereas before it took 22 hours to upload... and then failed.

I'm using the quick start esphome.yaml with this:   
nextion_update_url: "http://192.168.1.1:8123/local/nspanel.tft"

I'll let you know if it works this time...

**Comment by pehovorka** [comment]
Hi, it has already happened to me two times. Flashing the blank TFT helps to get rid of the `System Data ERROR!` and errors in the console, such as `Reading from UART timed out at byte 0!`. I am not sure how I fixed it the first time, but what I think helped the second time was to download the [nspanel.tft](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel.tft) locally and use it instead of downloading it from the remote repository. That way, the device does not need to decrypt HTTPS, and the upload should be generally faster. See more here: https://esphome.io/components/display/nextion.html#uploading-a-tft-file

You just need to download the file, store it somewhere where it is available on your local network and then change the `nextion_update_url` in the nspanel.yaml the same way as when uploading the blank tft.

**Comment by pehovorka** [comment]
Ohh, you already did the same thing! 😁

**Comment by iamandymcinnes** [comment]
That got it this time :)

**Comment by deejaybeam** [comment]
Hi
I agree with you, using a local path to upload the tft is the best option. Our idea was to keep the installation of the solution as simple as possible, so we decided to set the repo-url as default. This seems to work as long the file does not have support for all those languages which increases tft-size from ~1.8MB to ~8MB.
Baud rate is another thing. This should be solved now. It looks like, there are different revisions/versions around, with different default-settings (baud-rate of the nextion itself) but this can be set in the tft itself, which it is now.
The blank.tft should be only necessary if you came from joBr99/nspanel-lovelace-ui.

**Comment by T3mplate-wow** [comment]
Same problem here. TFT Upload running since 10h and is at 45% at the moment. 
Can you explain:
1. How to flash the TFT to get rid of the `system Data Error`. I got this also in previous tests and the only way I fixed this was to go back to Lovelace and then flash the white screen again. I was not able to fix this within this project.
2. What exactly to do to update the TFT faster. Which file I have to put on which location and where do I have to change the URL.

What I understand is:
1. Download the nspanel.tft
2. Put this file into config/www
3. after this the file is reachable unter  "http://IP_HomeAssistant:8123/local/nspanel.tft“
4. change the URL in the ESPHome Home Assistant Project in the „do not change anything“ area from: `nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft“`
to
`nextion_update_url: "http://IP_HomeAssistant:8123/local/nspanel.tft“`

is this right?


In the baud rate discussion there was written, that to change the baud rate you have to delete everything between the `Do Not Change Anything` brackets and replace it with the complete code of the `nspanel_esphome.yaml`. I am wondering, because the URL link is not included in this yaml file.
