### ISSUE TITLE
`Bug` Since 4.3.4 custom button for dimmable color light only turns on/off

### ISSUE THREAD

**Issue by MichaelHeimann** [Blackymas/NSPanel_HA_Blueprint#2072]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

EU

### What is the bug?

I've attached a deconz lightgroup to a custom button and before 4.3.4 I could dimm and change the color after tapping the icon. Now it just turns on/off.

This is the configured entity:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3189562/eb698394-bc93-4c75-bf15-74f68ec65f89)

### Steps to Reproduce

1) Assign deconz lightgroup as custom button
2) tap it
3) have no popup to change lightlevel/color

**Comment by edwardtfn** [comment]
I'm trying to find what is causing the issue here...

From `supported_features`, I can find your light supports the following:
```yaml
EFFECT = 4
FLASH = 8
TRANSITION = 32
```
And from `supported_color_modes` I cannot find a reference to brightness... 😞 

It is quite odd, but I see the same behavior with some of my lights here, so I can duplicate the issue.
I will work a bit more on this and come back when I have a solution...

**Comment by edwardtfn** [comment]
I believe I have a fix for this in `dev`. This will be included in the next release.
