### ISSUE TITLE
ESPHome 2024.6.0 won't compile

### ISSUE THREAD

**Issue by jfrancais** [Blackymas/NSPanel_HA_Blueprint#2161]
### TFT Version

4.3.8

### ESPHome Version

4.3.8

### Blueprint Version

4.3.8

### Panel Model

US

### What is the bug?

New version of ESPHome 2024.6.0 has a breaking change for OTA section

##### OTA PASSWORD #####
ota:
  id: ota_std
  password: ${ota_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

needs to be updated for breaking change.  Likely needs nspanel_esphome_core.yaml to be updated to 

ota:
  platform: esphome
  id: ota_std
  password: ${ota_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

**Comment by BluThunder2k** [comment]
+1

**Comment by edwardtfn** [comment]
Fixed!
Please try again and let me know the results.
It will be v4.3.9 now.

**Comment by BluThunder2k** [comment]
Compiled first shot!   Thanks!!!

**Comment by jfrancais** [comment]
Fixed.  Thanks!

**Comment by M0uC0** [comment]
Just to add a problem i had.. and how i solved it.

I usually "Clean Build Files" before update..
And because I'm using:

ota:
  password: !secret ota_key

 on customize area

"Clean Build Files" wouldn't complete.

Only after adding

ota:
  platform: esphome
  password: !secret ota_key

Then the "cleaning" finished with sucess.
