### ISSUE TITLE
`Bug` TFT update speed has been 115200 for quite a few versions

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#2230]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

US

### What is the bug?

TFT update speed has I my been 115200 for quite a few versions. Used to be able to use 921600. 
according to logs it tries 921600 then fails and reverts to 115200. When higher speeds were first introduced months ago I had no issues. Is there some way to force the high speed? I have it set as 921600 in the device config in HA. I even tried slower speeds with no luck.

**Comment by edwardtfn** [comment]
I will look at this...

**Comment by edwardtfn** [comment]
This is hard to troubleshoot, but I believe it was fixed in `DEV` and I'm even planning to change the recommended baud rate for all operations to 921600bps (which hopefully will allow image transfer one day).
I will close it for now, but please feel free to reopen it if you still having this issue after updating to the new version (to be released).
