### ISSUE TITLE
Add on_multi_click function

### ISSUE THREAD

**Issue by pawellygan** [Blackymas/NSPanel_HA_Blueprint#259]
It might be a good idea to add on_multi_click so a physical button could have single and double click - I used to have double click in my panel with Tasmota installed

**Comment by Blackymas** [comment]
what do you use the double click for?

**Comment by deejaybeam** [comment]
I (personaly) don´t like the multi_click function (double click) because this adds a delay to single pess.
And why do you need it - you have 32 virtual buttons?

**Comment by deejaybeam** [comment]
@trondtorsoe this is a nice idea, but from my point of view not possible with esphome an blueprint.
The reasons are:
- the blueprint can not change how the firmware is build from esphome side
- there is nor possibility to change what type of code should be compiled on esphome side
- currently if the button is pushed (off->on) the message is send to ha witch executes the action
- if you want something like a double click it has to wait for:
- release of the button and in a timeframe if the button is pressed again -> double click

this is how it works - if we would just add a double click, then it also always executes the short click, or we have to wait if there is a 2nd click, this always adds a delay

if the delay is too short, then the double click is not detected, if the delay is to long it takes some time if after a single click the action is executed - in addition to the round-trip time to ha and to exec the automation this is a bad idea for all others that dont use double-click

what is possible is to add a hold -  but this also means that the action accours on release not on push, but a little bit better.

The hold action should call the detail-page of the entity like the virtual buttons.

If you could give me a practical solution how to solve this problem you are welcome to send a pull request

**Comment by Blackymas** [comment]
> I think is is a good idea to be able to choose an action for double-click on the physical buttons. Single click can for example on/off entity or run a script - while double-click can run another script ....
> 
> If @deejaybeam leave the field for double-click - there will be no delay if the code listen for it....

i also think it makes no sense - technically a big problem as @deejaybeam  has already described

on the other hand we have 32 buttons and extra care that you can navigate from the home page to all pages quickly - so right / left / up / down

**Comment by stevoh6** [comment]
> @trondtorsoe this is a nice idea, but from my point of view not possible with esphome an blueprint.
> The reasons are:
> - the blueprint can not change how the firmware is build from esphome side
> - there is nor possibility to change what type of code should be compiled on esphome side
> - currently if the button is pushed (off->on) the message is send to ha witch executes the action
> - if you want something like a double click it has to wait for:
> - release of the button and in a timeframe if the button is pressed again -> double click
> 
> this is how it works - if we would just add a double click, then it also always executes the short click, or we have to wait if there is a 2nd click, this always adds a delay
> 
> if the delay is too short, then the double click is not detected, if the delay is to long it takes some time if after a single click the action is executed - in addition to the round-trip time to ha and to exec the automation this is a bad idea for all others that dont use double-click
> 
> what is possible is to add a hold -  but this also means that the action accours on release not on push, but a little bit better.
> 
> The hold action should call the detail-page of the entity like the virtual buttons.
> 
> If you could give me a practical solution how to solve this problem you are welcome to send a pull request
> 

hold is very nice idea, i will try push pull request for it ( esphome file) next week :)

**Comment by Blackymas** [comment]
@stevoh6 
hold we have already built in.
I hope we still make it for the release 3.1.0

**Comment by joostjdj** [comment]
I was looking for this too. In the meantime you can use the  [ slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml ](url) blueprint as a workaround. Create a helper as a dummy switch for the ns panel to switch and let the extra blueprint react to the ns panel physical button press. With this I manage to turn my lights on at 50% with one press, 100% double press and off by holding it.
The only downside is that the status of the light isn't represented on the NS panel. So I hope native support will happen in the future.

**Comment by deejaybeam** [comment]
Very nice solution! This could be a possible solution to add Double-click into the Blueprint.

**Comment by deejaybeam** [comment]
Now have tested the solution with bad results.
Single/Hold is possible with blueprint, but a double click detection is not possible with the current blueprint because it runs in paralell mode. This means a double click could be detected, but the first click always executes the single-click-action. I would like the idea of the liked blueprint solution very much, because there is no dely if you don´t assign a double click-action and you can assign the delay (also add a second delay-time for hold) to your needs, but this can not be implemented this way in the existing solution - sorry.
Anyway - this brings me to another idea for the hold - stay tuned.

**Comment by marcelo-lara** [comment]
+1
I personally use 'hold press' to turn off all my devices when leave: It would be nice to have this feature on the nspanel too =)

**Comment by deejaybeam** [comment]
Custom hold is implemented in beta-branch.
Install beta, or wait for new release.

**Comment by jjnj023** [comment]
Is it possible to add an option in the blueprint to change the behaviour of the long press? I would like to add a additional funtion to the long press. For example trigger an action that runs a script that turns off everything in the room.

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2

**Comment by jjnj023** [comment]
Great, I'll update ASAP! Tomorrow I'll install 5 more panels, so I'll have to update them. Very curious of the new work flow.
Thanks for all your efforts

**Comment by jjnj023** [comment]
I have to say, it works great this way.
For future reference and for others to follow:
I created a helper switch a and set that as the physical button 1/left in the blueprint. With another blueprint I let the system adapt to single (50%) and double press (100%). To let the status of the light reflect on the nspanel the other blueprint also switches the helper switch a back on (because the nspanel blueprint will turn it off by using the toggle option). This means that the indicator flashes a little, but will pull the state of the helper again once it's been set to on by the other blueprint.
In the nspanel blueprint I made a custom action to switch the light and the helper switch a off when long pressing the physical button.

There probably is a more elegant solution, but as a non programmer, this works for me.
