### ISSUE TITLE
Panel stays on boot page

### ISSUE THREAD

**Issue by Erkilaine85** [Blackymas/NSPanel_HA_Blueprint#336]
![IMG_20230213_175952](https://user-images.githubusercontent.com/122992225/218508368-7771acd0-d1bb-4846-a83e-1235cc7eb12d.jpg)

Has been like this for hours. Refresh not helping.

**Comment by sotatech** [comment]
Same here. The Blueprint seems to be running and I have tried Main and dev versions. I don't know if the fact that the Bluetooth: version field is empty is significant.

**Comment by Erkilaine85** [comment]
I have updated the blueprint and now its showing ver number but it still stays on boot 
![IMG_20230213_193219](https://user-images.githubusercontent.com/122992225/218533605-ed295a12-e8ff-4771-bdd3-40ae104e2ca3.jpg)

**Comment by JayBkr** [comment]
Have you followed this guide, it might help resolve your issue:

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-Stuck-on-Initializing

**Comment by deejaybeam** [comment]
> Same here. The Blueprint seems to be running and I have tried Main and dev versions. I don't know if the fact that the Bluetooth: version field is empty is significant.

I have done some changes in dev version to address this issue.
What have you installed from dev?
It is required to install/update:
esphome
blueprint
tft
from dev because the have dependencies
Even if you have updated the blueprint it is required to reload automations in HA

It is necessary that the blueprint version is shown in boot screen. If this does not appear, the blueprint fails to "talk" to nspanel.

Do you have ha-core 2023.2 installed?
This causes some issues with esphome and the changes in blueprint and esphome should help to avoid that.

You could try to turn the switch "Nextion inited" off and on again in the esphome-device.
This triggers the init-part of the blueprint again.

Of course, the blueprint has to be set up correct, otherwise this could not work

**Comment by Erkilaine85** [comment]
The thing is, i had this running for few weeks until today. After restart it stayd on boot. After that i have done everything by the latest guide. Last thing i tried was to delete blueprint and reinstalled it...and finnaly it booted up.

**Comment by sotatech** [comment]
Thanks @JayBkr @deejaybeam I Have installed everything you listed from Dev. I pulled down the latest .tft and uploaded that and copied/pasted the the blueprint - no change.
ESPHome was up to date and HA was on 2023.2.3 but I saw an update to 2023.2.4 so I applied that and after the restart my panel came to life!
I don't know if it was the HA update or just the reboot, but it's finally working.

Thanks.

**Comment by Blackymas** [comment]
so all is fine?

**Comment by sotatech** [comment]
Yes, I had wasted a lot of time trying to get the .tft uploaded from my Home Assistant that uses https. I'm not too sure what caused it to hang on boot, but it's working fine now and well worth the effort.
Thanks for all your great work!

**Comment by Erkilaine85** [comment]
> so all is fine?

So far looks solid.
