### ISSUE TITLE
Customize Home Screen

### ISSUE THREAD

**Issue by boojew** [Blackymas/NSPanel_HA_Blueprint#346]
I love this solution - I think it is amazing. I would like to suggest you add methods to customize the homescreen. IMO, is that I dont need the weather there, but rather I would prefer to be able to have scenes/scripts/entities there that I could control.

Thanks!

**Comment by Blackymas** [comment]
Thanks!

we are working on it right now so that you can customize it a bit more.

The weather is currently not affected. This is unfortunately not possible as it is with lovelace ui.

We have a different approach through the blueprint.

Therefore there are limits.

But it will be possible via blueprint come various things to freely allocate and icons etc to assign
