### ISSUE TITLE
Adjusting climate setpoint, up/down granularity too coarse

### ISSUE THREAD

**Issue by chris24walsh** [Blackymas/NSPanel_HA_Blueprint#350]
When I press up/down on the climate UI, it adjusts the setpoint by 0.5 degrees, which is too coarse for my liking. Can we adjust this to a different value, or is it hard-coded?

**Comment by nitruxa** [comment]
@chris24walsh see https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/345

**Comment by deejaybeam** [comment]
As alredy mentionded obove, we currently work on a big change regarding to the climate control (thanks to @nitruxa !).

**Comment by Blackymas** [comment]
have changed the label - should be possible
thanks to @nitruxa

**Comment by ronnieSVK** [comment]
Hey Guys !
First of all, thank you for this INCREDIBLE work ! Im speechless from result, what have you done.
Regarding to planned changes with "Thermostat". Do i understand correctly, that with next changes i should be able to "mirror" my Generic Thermostat created in HA to the panel (because if the possibility to set which entities should Thermostat page display and control) ?

Danke Sehr Jungs, Grüssen aus der Slowakei

**Comment by Blackymas** [comment]
hey
it took a long time but with the next version comes a completely new climate page.

You can already install the DEV version or follow this issue for it

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
