### ISSUE TITLE
Feature request: delayed off for the physical buttons

### ISSUE THREAD

**Issue by kchiem** [Blackymas/NSPanel_HA_Blueprint#400]
For a bathroom exhaust fan, it would be useful to have a delayed off functionality--to let it run another 10-15 mins before turning off.

Some sort of visual indicator when it's in the delayed off state would be nice too, such as a countdown icon or display of time left, and/or having the blue bar underneath the load flash on and off.

An ability to override to turn off immediately would be nice too, such as long pressing the button.

**Comment by Blackymas** [comment]
with version 3.2 there will be a new function for the hardware button for long press.

Here you can then deposit your own programming.

Generally your logic should be built in HA. You can create a helper switch and put an automation under it that takes this delay into account.

It is difficult to build in every special case in the NSPanel itself. Since some do not need this function.

But you have two solutions 

1. to solve the whole thing with a helper and HA automations

2. with version 3.2 you get the possibility in the Blueprint to deposit an own programming.

**Comment by kchiem** [comment]
I figured I could do the delayed off in HA itself, but will 3.2 allow me to show that it's in this state (icon, timer, and/or blinking blue line) ?

**Comment by Blackymas** [comment]
the "blue line" will not change with v3.2 - this line will only change based on the status of the entity.

If you want a blinking etc. you have to add this to the code yourself.

i would say wait for v.3.2 and check it out ;)
