### ISSUE TITLE
Hot water charge button doesn't show up unless climate entity is linked

### ISSUE THREAD

**Issue by kchiem** [Blackymas/NSPanel_HA_Blueprint#401]
Can this be linked to the icon for the hot water temperature on the home page?  It's the same icon already.

**Comment by Blackymas** [comment]
if i understand you correctly, you don't have climate but want to use the hotwater button?

**Comment by kchiem** [comment]
Well, sort of.  I don't want to use this to control my hvac, but I do want to show the hot water temp and the summon hot water from it.  My hot water has nothing to do with my climate control.

**Comment by Blackymas** [comment]
Then you can just take one of the 32 buttons

**Comment by kchiem** [comment]
Why not take the "hot water charge button"?  Except that for some reason, it's hidden in a climate control section, while the hot water temperature is shown on the home screen using the same icon?

**Comment by kroon040** [comment]
Here, the same. I have a binary sensor for hot water and it's controlled from my hvac boiler. It's very nice to see in the home screen also that hot water usage is on (mostly there is someone in the shower)

**Comment by Blackymas** [comment]
with version 3.2 hotwater temp was deleted and replaced by a free variable.

It makes no sense to put this button on the homepage, because it is too special.

Why is it a problem to use one of the 32 buttons?

By the way, in version 3.2 the icons for the buttons and the icon color can be freely assigned.

You can then use a Hotwater icon and assign a color.

**Comment by kchiem** [comment]
> It makes no sense to put this button on the homepage, because it is too special.
> 
> Why is it a problem to use one of the 32 buttons?

It's pretty useful to have it on the home page for an NSPanel installed in a bathroom..

**Comment by Blackymas** [comment]
then use a button or the HW buttons

**Comment by kchiem** [comment]
Can those buttons be configured to show hot water temp?

**Comment by Blackymas** [comment]
> Can those buttons be configured to show hot water temp?

???

please don't get me wrong.

But it is really a very special case.

If I summarize this results in the following

1. you have a climate in the room and thus no climate side
2. you don't want to use any of the 32 buttons
3. you don't want to use a HW button

There are 3 variants how you can build it. 

For an extra Hotwater button on the home page is no more place and this special case have maximum 10% of the people bze who also no solution of the 3 points above want to use.

I can understand your concern but I have to look at the whole project.

That's why in version 3.2 humidity and hotwater were deleted and 3 free fields were added so that everyone can use it as he needs.

**Comment by kchiem** [comment]
What is this "no more place" deal?

Right now, there's a hot water temperature on the home page.  Next to it is an icon, the same one used for the hot water charge button in the climate page.  All I want is for that icon on the home page, to also trigger the hot water charge if pressed.

**Comment by Blackymas** [comment]
as I wrote

"That's why in version 3.2 humidity and hotwater were deleted and 3 free fields were added so that everyone can use it as he needs."

**Comment by kchiem** [comment]
Can those free fields act like buttons if pressed?  Otherwise, it doesn't really change anything.

**Comment by Blackymas** [comment]
I've explained - there are only display fields for sensors that can't be combined with a button, that's not technically possible.

One would have to add an extra button especially for your case. As I have already said, a button on the new sensors makes no sense and we currently have no other place for it.

Why can't you use a button that exists, you have 32 buttons + 2 hardware buttons.

You also have a fast navigation. if you swipe left, right, up and down from the homepage, you always get to a different button page

**Comment by kchiem** [comment]
This started on the current 3.1 version, where the hot water temperature is already shown on the home page, with an icon identical to the hot water charge button that's clickable in the climate page, but not on the home page.  Why is it technically possible on the climate page but not the home page to make an icon clickable?

But now you're saying, oh, that hot water temp on the home page is going away, being replaced by something customizable. 
 Ok, and I'll end up customizing it to show the hot water temperature with a similar icon.  And we're back to, why can't that temperature/icon be made clickable as well?

Someone else might have an NSPanel near a garage door or gate, and might configure a field to show whether the garage door or gate was opened or closed, and could benefit from having that field clickable to toggle the state of that barrier as well.  Or maybe it's an electronic door lock?  Or the state of an alarm system?  Etc.

**Comment by Blackymas** [comment]
create a poll request under discussions, if there are enough other people who need it i'll think about how i can implement it
