### ISSUE TITLE
Entities page values not updating unless re-opened

### ISSUE THREAD

**Issue by NeilDuToit92** [Blackymas/NSPanel_HA_Blueprint#410]
I noticed that when I have one of the Entities pages open, the values don't update.

**Reproduction Steps**
1. Add light as Entity 01
2. Navigate to Enitities Page 1
3. The added light shows as 'off' 
4. Manually turn on the light
5. The page still shows light as 'off'
6. Navigate away from page (Home or another Entities Page)
7. Navigate back to Entities Page 1
8. The light now shows as 'on'

Tested the same thing by adding the light to Button 01 and it reflects state changes immediately.

**Comment by Blackymas** [comment]
Hello,

this is not a bug this is not wanted.

When the entitypage page is called, the sttus of the entity is loaded and displayed.

The fields are all local and not global. This is due to the low memory of the esphome. Therefore we are forced to reload the state of the entities every time the entity page is called. 

This has the advantage that we always have the current status.

Nobody stands in front of the display and switches something with the cell phone or similar and watches on the entity page if the status changes.

Would also have the extreme disadvantage that we would generate a high load on the part of HA and blueprint, if we would build for each entity an additional trigger.

The normal process is as follows.

You go to the nspanel jump to the entity page and see what the current status is. After a short look you go away from the NSPaenl again. So in our opinion it makes no sense to add additional updates here. You only need the current state

Furthermore it would mean more load for HA and esphome.

there are no plans to change anything here.
But thanks for your report :)

**Comment by NeilDuToit92** [comment]
Hi,

My scenario is to set the display timeout to 0 and then navigate to Entities Page 0, so the panel stays on that page.
Then I have entities on there like a few timers and the current power consumption of my house, which I wan to be able to see at a glance.
I don't want to get up from the couch every time just to go and switch to the page to see my timers.

Is it possible to display a handful entities on the home page or somewhere that can achieve this that I missed?

**Comment by bommel947** [comment]
I have exactly the same usecase as mentioned from @NeilDuToit92.
WAF is very low. 
Even an update - lets say: every minute would be very helpful.

**Comment by edwardtfn** [comment]
> Even an update - lets say: every minute would be very helpful.

That is probably feasible.

**Comment by Blackymas** [comment]
fixed
