### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by egrinaldi** [Blackymas/NSPanel_HA_Blueprint#411]
Hi, I've been following this project and I'm impressed, and would like to implement it on my devices, although I think the UI could be improved, and I would be glad to help. I've created an interface for my personal NSPanels that I would like to share with you. My version is not using the blueprint, but I could work on upgrading your version. Let me know if you're interested. I could not find any other way to contact you, so sorry to open a ticket. Thanks!

![IMG_1555](https://user-images.githubusercontent.com/36819066/224129193-9457dd24-b03f-4f03-84a4-952329885109.jpeg)
![IMG_1558](https://user-images.githubusercontent.com/36819066/224129201-6741d16e-944d-46ec-a5be-1b6a5d78cdc5.jpeg)
![IMG_1557](https://user-images.githubusercontent.com/36819066/224129209-1014bd56-61f7-4999-9d69-100ffb9ea289.jpeg)
![IMG_1556](https://user-images.githubusercontent.com/36819066/224129210-c633b429-6383-4e76-9854-453191cfd725.jpeg)

**Comment by Blackymas** [comment]
Hello,
design looks ok. But we do not plan to change extremely much in the design, because this design has led to the success of this project.

But with version 3.2 will come a big change. Every icon as well as every icon color, text color etc can be changed via blueprint.

So everyone can build his own panel only the positions remain.

But you are welcome to customize your version and present your project under discussions -> show and tell ;)
