### ISSUE TITLE
Settings page back to home page

### ISSUE THREAD

**Issue by roccojay12** [Blackymas/NSPanel_HA_Blueprint#489]
When you hold the clock to go to the settings page then click the X to close the page it seems to get stuck on loading screen even tho no entities are incorrect.

Doesn't happen 100% of the time just the odd few times

Reboot solves the issue for now

**Comment by Blackymas** [comment]
This is certainly due to some entity you have selected and is displayed on the home page. There seems to be some state that does not fit.

Or in your network the last command is lost.

You can adjust the delay vai HA NSPanel device and see if it gets better.

I have just tested the scenario 20 times in a row without problems.
