### ISSUE TITLE
Sensor text for the new homescreen sensors

### ISSUE THREAD

**Issue by andytuinman3** [Blackymas/NSPanel_HA_Blueprint#490]
More of a feature request.

I have a sensor which tells me which garbage bin (plastic,regular waste,garden waste,paper) has to go on the road for it to be picked up the next day. 

The sensor has the following text

If none has to be put on the street it says: Geen    (dutch word for None)
If any garbage bin has to be put on the street tomorrow it shows the name of the bin (GFT, Restafval, Papier or PMD)

But the page hangs on loading because it doesnt have a unit of measurement)

Executed: March 20, 2023 at 10:54:12 PM
Error: Error rendering data template: ValueError: Template error: round got invalid input 'Geen' when rendering template '{{ states(repeat.item.entity) |round(1) }}{{ state_attr(repeat.item.entity, "unit_of_measurement") }}' but no default was specified

As you can see the state "Geen" is invalid. But it's exactly what I want to see. 

Is there a possibility it just shows the state for some entities without a unit of measurement?

**Comment by rafaelmaza** [comment]
Investigating this a bit deeper, I think it goes beyond not having a unit of measurement (although related). 

I tried to add a generic unit of measurement to my categorical sensor, and it still failed. I believe this is because the template *assumes* a numeric value for the sensor, therefore tries to round it (with 1 decimal point), which is also the operation that failed in your example (`round got invalid input 'Geen' when rendering...`).

As a workaround, this *assumption* could be removed from the template by replacing [this line](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_blueprint.yaml#L9216) (and the following 2 like it) with something similar to this code:

```
message: '{{ trigger.event.data.new_state.state |round(1) ~ " " ~ trigger.event.data.new_state.attributes.unit_of_measurement if trigger.event.data.new_state.attributes.unit_of_measurement is defined else trigger.event.data.new_state.state }}'
```

**Comment by edwardtfn** [comment]
If you take a look at #514 im focusing at this issue about rounding and I'm proposing check if it is a number before sending to the panel.

**Comment by andytuinman3** [comment]
> If you take a look at #514 im focusing at this issue about rounding and I'm proposing check if it is a number before sending to the panel.

This works great. My panel now shows the correct trashbin and the date when it needs to go on the street. I hope this will find it's way to main.

![16796112988173108213838391886982](https://user-images.githubusercontent.com/4999564/227380677-0d3a3ba9-9cb5-45fc-88cf-4431ec06bd24.jpg)
