### ISSUE TITLE
Display is showing decimal places

### ISSUE THREAD

**Issue by Boarder** [Blackymas/NSPanel_HA_Blueprint#546]
Display is showing decimal places, but in the state field there are none. 
And a space to the unit  is missing

![2023-03-27_07-40-34](https://user-images.githubusercontent.com/45979973/227852103-8345e08e-857d-409b-9352-1c0d28b721bf.JPG)

Great project :-)

**Comment by edwardtfn** [comment]
Which version are you using?

**Comment by Boarder** [comment]
I´m using the latest v3.2.1
and no HA shows me in the state no decimal places

**Comment by edwardtfn** [comment]
Yeah, but what HA displays is different from what HA sends to the automations. Since v2023.3 it is possible to know your precision selection, but implement that in the blueprint would force all users to migrate to this version (or use older versions of the blueprint), which maybe should be the way to go in a near future.
Currently, the minimum required HA version is 2022.11, so we are talking about pushing 4 months only, which looks quite feasible, however, we are talking about a version released less than a month ago, I'm pretty sure many people still don't have that.

**Comment by Blackymas** [comment]
this is not a bug. We get the value from HA and put it into a field. 

We don't change anything in the value but take over what we get from HA.

technically also not possible that we convert this automatically and put a "." ;)

Look under developer tools and search the entity then there should be the value that HA passes to us.

**Comment by Boarder** [comment]
well thats the value it shows me under developer tool, no ".0", mayby i´m looking wrong?

<img width="387" alt="Screenshot 2023-03-29 185151" src="https://user-images.githubusercontent.com/45979973/228612008-bf94e986-f859-406a-814e-ff2f8b1b6566.png">

**Comment by rleongcs** [comment]
Having the same issue. I have made sure I set HA display precision. So not sure if what is sent behind the scene is different than what is shown on the UI?

![image](https://user-images.githubusercontent.com/61628312/234078199-34e84caa-eda0-4733-9f3b-1736cb04298e.png)
![image](https://user-images.githubusercontent.com/61628312/234078280-83e57068-727d-4ff7-a15a-f7a37dec4780.png)
![IMG_1580](https://user-images.githubusercontent.com/61628312/234079270-bbd1a1e7-7ce1-4e5d-8ead-e5ff135aa01c.jpg)
