### ISSUE TITLE
[nextion:396]: Nextion reported variable name invalid!

### ISSUE THREAD

**Issue by rleongcs** [Blackymas/NSPanel_HA_Blueprint#789]
I was just updating two of the NSPanel to the latest ESPHome v2023.4.4 and one of them had the below error which I don't remember seeing earlier after Blueprint v3.3 update.

Is this issue some config on the blueprint file or code?

![image](https://user-images.githubusercontent.com/61628312/236491361-af1239a2-3231-4bee-8271-bafbac7d34a5.png)

**Comment by edwardtfn** [comment]
It's hard to say exactly which is in your case, but we have a known issue when the entity assigned to the hardware buttons returns so,e thing diferent ham `on` or `off` on it's states, which could be just a temporary thing or could happen all the time if you have like a scene or an automation assigned to those buttons.
In any of those cases, you shouldn't worry about the error message, as it won't affect the functionality, however you could be seeing incorrect state on that blue bar representing each of those entities in the screen.
Anyway, that was already fixed in `dev` by #776 and will that fix will be included in the next release.

**Comment by rleongcs** [comment]
I know what is my case...the 2 physical buttons are assigned to scenes. 😉

**Comment by itslennie** [comment]
I had The Same™ errors occuring in the log, maybe 40-50 a second, which was impacting the panel performance.  A recompile of esphome has reduced that to 4 or 5 errors a minute.  I do have relay1/2 switches define on ESPhome light switches (on/off) and also have explicitly defined the label names.

It's not impacting the device now which is great. Look forward to the roll-up of 776. 

![image](https://user-images.githubusercontent.com/42844738/236613981-c157ab66-e927-4682-9f78-60fe7076b10b.png)

![image](https://user-images.githubusercontent.com/42844738/236614006-05b963c4-5391-413e-bdc1-dc62b7e2f3b4.png)

**Comment by edwardtfn** [comment]
It looks like you have a different issue than he one fixed by #776.

Do you have this even when your panel is sleeping?

Could you please share your blueprint settings as yaml?

**Comment by itslennie** [comment]
so, it looks like my blueprint was out of date, and perhaps the panel tft.  I've repulled these along with an esphome update, and now the issue for me is resolved.

**Comment by Blackymas** [comment]
perfect - thanks for feedback
