### ISSUE TITLE
Adding New Languages

### ISSUE THREAD

**Issue by jchenny7** [Blackymas/NSPanel_HA_Blueprint#797]
Would it be possible to add extra languages and characters?

I have tried typing in Chinese in the Blueprint Automation, but there seems to be some characters missing and not all characters were able to be displayed successfully. 

Thank you.

**Comment by edwardtfn** [comment]
I believe this have the same root cause as #664.

**Comment by rleongcs** [comment]
@edwardtfn I am not sure if it is totally the same root cause. #664 might solve the length issue but there is another issue from my testing. It seems certain characters are not displayed even though it has not reached the character limitation. I felt it is something to do with the font set that are used or something along those lines.

Below are the tests I did...
![IMG_1641](https://user-images.githubusercontent.com/61628312/236874826-87330428-ba2f-4467-a1aa-ec752d5fa4fb.jpg)
![image](https://user-images.githubusercontent.com/61628312/236875936-45ede0ef-652e-49e5-b308-6cc0bcdcbdcd.png)
![image](https://user-images.githubusercontent.com/61628312/236876016-264f8da8-d83e-4113-872a-b41159d95dad.png)


![IMG_1642](https://user-images.githubusercontent.com/61628312/236875193-de45f1c6-162b-494d-8875-5f4a9a7d70c4.jpg)
![image](https://user-images.githubusercontent.com/61628312/236875448-3986b47e-79f6-4a62-b288-1ad126820344.png)
![image](https://user-images.githubusercontent.com/61628312/236875531-acbe0b1a-ee9c-482b-ac14-91ea8508becf.png)
![image](https://user-images.githubusercontent.com/61628312/236875671-c2e0fb69-5ea1-4ef7-aae8-d5a984f0451d.png)

**Comment by edwardtfn** [comment]
Is it possible to send those chars here as text? I want to run some tests here.

**Comment by rleongcs** [comment]
Here you go...the ones with 2 sets of data is the one on the left is Simplified Chinese and right is Traditional Chinese.

1. `浴室二`
2. `房间走廊` `房間走廊`
3. `门厅` `門廳`
4. `走廊`
5. `入口分隔`

**Comment by bluefoxlee** [comment]
Due to limitation of Lcd memory, wonder will that be better to let user/team to create their own language tft, just like Tasmota to lower the tft size. And either host by themself or/and contribute to the project. especial for CJK language.

I did a quick test by add few Chinese characters with ubuntu font, and generate the custom tft. Which is working ok to display the extra characters I would like to use. The common use characters for T.Chinese is around 4,808 which is almost impossible to include them all in to tft. I guess the best solution for Chinese user will be collect necessary characters only and generate separate tft.

**Comment by bluefoxlee** [comment]
Here is the crazy test result. Add both ID:0 16 and ID:1 18 font with full 4,804 T.Chinese characters set.

![2023-06-11-19-50-08-714](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/dd3a1503-7781-4c78-8994-77d7f41694f0)

![2023-06-11-19-52-12-835](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/9430133e-8685-449a-941c-60fc21d43d9d)

**Comment by jchenny7** [comment]
> Here is the crazy test result. Add both ID:0 16 and ID:1 18 font with full 4,804 T.Chinese characters set.
> 
> ![2023-06-11-19-50-08-714](https://user-images.githubusercontent.com/894044/244934746-dd3a1503-7781-4c78-8994-77d7f41694f0.jpg)
> 
> ![2023-06-11-19-52-12-835](https://user-images.githubusercontent.com/894044/244934751-9430133e-8685-449a-941c-60fc21d43d9d.jpg)

Wow, would you kindly share your modified TFT file? 
Thank you.

**Comment by bluefoxlee** [comment]
> > Here is the crazy test result. Add both ID:0 16 and ID:1 18 font with full 4,804 T.Chinese characters set.
> 
> Wow, would you kindly share your modified TFT file? Thank you.

Sorry @jchenny7 I did not see your comment until now. Try to @ you if you still need it.
However, it's more for T.Chinese rather than S.Chinese. since I don't have common use S.Chinese characters set on hand.

**Comment by jchenny7** [comment]
> > > Here is the crazy test result. Add both ID:0 16 and ID:1 18 font with full 4,804 T.Chinese characters set.
> > 
> > 
> > Wow, would you kindly share your modified TFT file? Thank you.
> 
> Sorry @jchenny7 I did not see your comment until now. Try to @ you if you still need it. However, it's more for T.Chinese rather than S.Chinese. since I don't have common use S.Chinese characters set on hand.

T. Chinese would be perfect, which is the language we commonly use in Taiwan. 
Thank you.
