### ISSUE TITLE
48 hours upload, and it did not work

### ISSUE THREAD

**Issue by PatrikPatrik2** [Blackymas/NSPanel_HA_Blueprint#857]
When I press the "Update TFT display" from home assistant, it took slight more than 48h for the upload. It ended up with the screen beeing completely white. I made a power reboot and the screen wrote error. The ESP32 part still works OK. Below is the ESP32 configuration. Is there some baud rate missing?

`substitutions:

###### CHANGE ME START ######

  device_name: "sonofpanel1" 
  wifi_ssid: "ssid"
  wifi_password: "passwrf"

#  nextion_update_url: "http://192.168.2.89:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by PatrikPatrik2** [comment]
I have restated the update - the progress is slow as before - but when I look at the log in ESPhome it writes

[11:01:37][E][uart:015]: Reading from UART timed out at byte 0!
[11:01:37][W][nextion:072]: Nextion is not connected! 
[11:01:37][E][uart:015]: Reading from UART timed out at byte 0!
[11:01:37][W][nextion:072]: Nextion is not connected!

**Comment by deejaybeam** [comment]
the way you have postet you configuration makes it hard to read, but it looks like you have activated nextion_update_url 2-times:
first with local URL - HIGHLY recommended
second with http(S) remote URL to this repo

2nd one will overwrite 1st one, this means you try to upload the tft from this (remote) git-repo via httpS!
feels like this is discussed here 1000 times: DON´T do this - only in some very rare cases this works because of X-factors that could cause problems AND it is recommended NOT to use httpS (SSL) to write the TFT to the panel.

I´m pretty sure this is your problem - its x-times reported, that uploading TFT via httpS://raw.github.... takes ages, and the chance to corrupt the data while flashing this way is very high - that results in the "white-screen"

Pleas read the docs here or search the issues or have a look here: https://esphome.io/components/display/nextion.html#uploading-a-tft-file

Use your homeassistant as a plain http-server and try to upload the blank tft now at first
If this works, uload the full tft again - with plain http on a local server this should be done in ~15 minutes

tip for posting code:
use the "add code" button, or use tripple backticks "```" to surround your code-posting
and the preview to see how it looks like - this would make your postings readable

**Comment by edwardtfn** [comment]
As @deejaybeam mentiined, this TFT upload shouldn't take more than 15 to 20 minutes. If it's taking more than 30min, I would cancel it and try again as I never seen any of those long transfers ending successfully.

I would suggest you to take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Uploa

**Comment by PatrikPatrik2** [comment]
Thanks, now I got it to work. Thanks for excellent support

**Comment by deejaybeam** [comment]
> As @deejaybeam mentiined, this TFT upload shouldn't take more than 15 to 20 minutes. If it's taking more than 30min, I would cancel it and try again as I never seen any of those long transfers ending successfully.
> 
> I would suggest you to take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Uploa

Link should be: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload
