### ISSUE TITLE
BLE Support?

### ISSUE THREAD

**Issue by GeorgyErm** [Blackymas/NSPanel_HA_Blueprint#871]
Is it possible to add BLE or Bluetooth support of standard ESPHome Bluetooth proxy or BLE Tracker components?

**Comment by bkbartk** [comment]
probably but you should read this first I think
https://esphome.io/components/bluetooth_proxy.html
Then just add it to the configuration, probaly using the arduino framework as not all components work on esp-idf yet.

but check the warning about stability, you will find out if it works or not

**Comment by edwardtfn** [comment]
The memory of the ESP used for NSPanel is not sufficient to hold both the files of this project and Bluetooth proxy simultaneously.

**Comment by Blackymas** [comment]
@edwardtfn described the problem

**Comment by Phhere** [comment]
Maybe it is possible to make a new try on this with version 4? 
I am not sure weather it would be an option to remove the web_server and captive_portal component and strip down the memory footprint

**Comment by bkbartk** [comment]
So, removing captive portal might would do the trick. 
min this article. 
https://blakadder.com/nspanel-teardown/
I see 16MB of paramount is available. Not sure how this works. Seems to be available by GPIO. That might be a performance issue. 
But if not and someone can make this work. One would have more space for features.

**Comment by edwardtfn** [comment]
> So, removing captive portal might would do the trick.

It doesn't.
I've tried just now without the captive portal and adding bluetooth_proxy (and changing the wifi power saving mode, as for some reason the bluetooth proxy requires some) and it is still failing to compile:

```
Linking /data/office-workstation-panel/.pioenvs/office-workstation-panel/firmware.elf
RAM:   [==        ]  17.3% (used 56824 bytes from 327680 bytes)
Flash: [==========]  104.0% (used 1907713 bytes from 1835008 bytes)
Error: The program size (1907713 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================= [FAILED] Took 167.49 seconds =========================
```

> I see 16MB of paramount is available. 

This is RAM memory, and we are OK with that. The problem is with Flash memory as it is 4MB and only part of this is available for our code.

Again, it exceeds by just a bit, but even if you get there removing some functionality (I can anticipate removing the web will break the json parser used by some components) to the point you get this installed, it will prevent future features.
Maybe you can copy the `nspanel_esphome.yaml` locally and try remove some functionality that doesn't apply for you. It will be an advanced installation, therefore not supported and a bit of work every time we release a new version, but you might get to your goal.

**Comment by fuzzysb** [comment]
My question is what components are in use that are incompatible with ESP-IDF? I see that there is a ESP-IDF Nextion Driver, and will support most of the configuration, just wondering if you can call out which are the issue currently? may be worth making a fork of this project to allow Bluetooth Proxy but with more limited feature set as I do not use anywhere near the full capability of this project. but room based device presence tracking i could get on board with, as i have all my M5 Switches using ESP-IDF and they do support Bluetooth Proxy, its just the NSPanel that uses this project (which i love and dont want to go back to my previous manual Nextion files for my NSpanel) that dont, and these are in my main living areas and bedrooms.

**Comment by edwardtfn** [comment]
> I see that there is a ESP-IDF Nextion Driver

Where can I find that?
Nextion is the only component requiring esp-idf support.

**Comment by fuzzysb** [comment]
https://github.com/Ligament/esp-idf-nextion-driver

**Comment by edwardtfn** [comment]
We are supporting ESP-IDF already.

**Comment by fuzzysb** [comment]
I saw on the update. the question is, has this changed the BLE proxy support in the panel or is this still unsuitable?
