### ISSUE TITLE
Screen randomly  wakes up. 

### ISSUE THREAD

**Issue by webhostsg** [Blackymas/NSPanel_HA_Blueprint#921]
It's been several weeks using v3.4 and I noticed that the screen randomly wakes up sometimes every 5 minutes. Currently using ESPHome Firmware: 2023.6.4. 

I also noticed that, the hardware button is sometime slow to respond. Left button is hooked up directly to my ceiling light and sometimes pressing it does not turn on the ceiling lights immediately, sometimes have to wait nearly 1 minute. Relay 1 local fallback is activated in blueprint.
![CleanShot 2023-07-08 at 00 18 33](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/cbd2b0fb-608f-44ca-9240-7ed5f056a0af)

Panel's screen showing : 
TFT: 3.4
ESPHome: 3.4
Blueprint: 3.4

![CleanShot 2023-07-08 at 00 15 10](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/c738ba98-f553-4893-8246-5120958e2c8b)

![CleanShot 2023-07-08 at 00 20 37](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/9375d4eb-ed99-497d-a976-8be4f923dd64)

Also why is the NSPanel event and Settings Entity showing some JSON values?
![CleanShot 2023-07-08 at 00 21 35](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/6be5395a-179a-4e9b-9170-b6be36a5b266)

**Comment by edwardtfn** [comment]
> It's been several weeks using v3.4 and I noticed that the screen randomly wakes up sometimes every 5 minutes.

I haven't noticed anything like this, but all my panels will wake-up automatically with presence, so maybe it's happening but I will never be there to see. Anyhow, I think you are the first one reporting this.
One thing you could do to troubleshoot this is to go into Logbook and look for what is happening with the `sensor.xxxxx_nspanel_event` as any page change should be visible there. And wake-up is basically leaving the page `screensaver`.


> I also noticed that, the hardware button is sometime slow to respond. Left button is hooked up directly to my ceiling light and sometimes pressing it does not turn on the ceiling lights immediately, sometimes have to wait nearly 1 minute. Relay 1 local fallback is activated in blueprint.

I'm working right now on changing this fallback engine. Currently, the fallback engine works locally only when your panel cannot reach Home Assistant, otherwise it will controlled by Home Assistant.
Basically, when you press the button, it will send this info to Home Assistant, where the Blueprint will be triggered and then send a command to your panel to toggle the relay. It should be almost instantaneously, but network issues or an overloaded Home Assistant could drive to some delay.
Also, is you want to troubleshoot, you could open the device page (the same on your picture) and try to see how long it takes to change the `Left Button` to `on` when you press the button manually. Then in that same page, change the switch related to Relay 1 and see how long it takes to turn on your light.
If those two are instantaneously, then you probably have some slowness when processing the Blueprint. Again, we hope to improve this for physical relays in the next version, but probably won't change for other entities, although the changes we are doing might reduce a bit the load on the blueprint, as we are moving some functionality to be processed directly on ESPHome.



> Also why is the NSPanel event and Settings Entity showing some JSON values?

This is not an error. It was implemented on v3.3 when NSPanel Event was introduced, replacing lots of other sensors (`currentpage`, `lastclick`, etc.) and the `Settings Entity` was already a CSV before and we changed to json-like as it makes easier to handle it's data and it reduces the chances of error (like when you have a coma in some string passed to the blueprint prior to v3.3).
This i also something we are changing with the next release. #887 replaces the Settings entity by HA events, again increasing reliability and cleaning up a bit this device page.
I have worked also on NSPanel event to go in the same direction, but I'm not sure if we will be able to remove that sensor on time for the next release.

**Comment by webhostsg** [comment]
> > It's been several weeks using v3.4 and I noticed that the screen randomly wakes up sometimes every 5 minutes.
> 
> I haven't noticed anything like this, but all my panels will wake-up automatically with presence, so maybe it's happening but I will never be there to see. Anyhow, I think you are the first one reporting this. One thing you could do to troubleshoot this is to go into Logbook and look for what is happening with the `sensor.xxxxx_nspanel_event` as any page change should be visible there. And wake-up is basically leaving the page `screensaver`.
> 

Logbook showing:
![CleanShot 2023-07-08 at 01 38 46](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/59a21bdc-6848-4e41-9d74-f31d41f09759)

**Comment by edwardtfn** [comment]
On this log I see it opening the Home page only 3sec after going to sleep. Have you clicked somewhere in the screen during those 3secs?

**Comment by edwardtfn** [comment]
Anyhow, it is something wrong there.
Don't you have any other automation (other than the one using the blueprint) calling services related to this panel?

**Comment by webhostsg** [comment]
@edwardtfn i think i know why it's waking up every 5 min, see screenshot of logbook below:

![CleanShot 2023-07-08 at 01 55 43](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/ead93af2-e3c9-4551-8bd9-42d554766d15)

**Comment by webhostsg** [comment]
Just checked the other NSPanel's logbook in the other room and that one does not randomly reboots

**Comment by edwardtfn** [comment]
It doesn't look like a reboot. It could be that your panel is loosing it's connection to Home Assistant, which would explain the delay on button press.
I can take a look in the code to make sure it doesn't wake-up when this happens, but you should take a look on your Wi-Fi on the place where your panel is.
How is RSSI level over time?

**Comment by webhostsg** [comment]
Monitoring RSSI now, at the moment:


![CleanShot 2023-07-08 at 02 14 44](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59085206/5b951043-146c-4fb0-95f5-6c5d5ade5a23)

**Comment by edwardtfn** [comment]
Looks good. Is the signal at good levels like this over time? (You can see the history for this sensor).
The api can disconnect due to some invalid data also, and you will be able to see this happening by monitoring the ESPHome logs over wireless.

**Comment by webhostsg** [comment]
@edwardtfn ok, I've just moved the NSPanel to the other node. So far seems the was no disconnection in 15min, did not notice the screen waking up within that 15min either. I'll monitor it for a day and will close this issue if everything is ok

**Comment by bkbartk** [comment]
Don’t know if this is related. 
but by default. If esphome can’t reach the ha api for 15 minutes. It reboots automatically. 
but you should be able to see this in the ha log

**Comment by webhostsg** [comment]
Issue has been resolved, random screen wake up was caused by WiFi connectivity issue. Connected NSPanel to a different WiFi Mesh Node to fix connectivity issue.
