### ISSUE TITLE
New Feature: 2nd climate entity

### ISSUE THREAD

**Issue by chief110** [Blackymas/NSPanel_HA_Blueprint#933]
Hello together,

thank you very much for the hard work.

I have underfloor heating and an additional appliance for airconditioning.

I would love to be able to control both.

Thanks in advance.

Hendrik

**Comment by Doughboy68** [comment]
It has been mentioned before that you can just assign a climate entity to any button and it will launch the climate page to control that particular thermostat. This is what I do to control fireplace in Family Room, but also able to control my main house ecobee thermostat. However, you cannot add separate chips or buttons for each climate, but my chips just display temps in different rooms so that is fine.

**Comment by hapklaar** [comment]
Was looking for the same feature, namely to control more than one room on the panel. I wasn't able to select any climate entities to custom or hardware buttons. Could you explain a bit more @Doughboy68 ?

**Comment by edwardtfn** [comment]
With v4.0 (currently on `beta`) you will be able to assign a climate entity to one of the custom buttons in the Home page and will probably satisfy this need.
