### ISSUE TITLE
Update TFT Problem - "HTTP Request failed"

### ISSUE THREAD

**Issue by lennartschulte** [Blackymas/NSPanel_HA_Blueprint#944]
[logs_nspanelworkshop_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12099734/logs_nspanelworkshop_logs.2.txt)
I'm sorry but i need to open last hope issue. 
Issue: I can't update my TFT on the panel. No matter what address i use (homeassistant/IP-Adress/Github). As you can see in the log i always get the same error: "HTTP Request failed" in the logs is also another error "Nextion reported variable name invalid!" which might be related or not.

I just compiled and updated the panel again with the current beta due to compatibility with the new ESPhome version.

Some main facts out of the log:
ESPHome version 2023.7.0
Nextion Firmware Version: 69
Nextion Device Model:     NX4832F035_011C
Home Assistant 2023.7.2
Local TFT File updated 2 weeks ago (should be up to date)

i also searched to other open and closed issues to see if anyone had the same issue. Although there were other similar issues, the solutions either did not work for me (Exit Parse) or there was a bit different issue or no solution at all as far as I saw.

**Comment by lennartschulte** [comment]
by the way: is also cannot use the blueprint but perhaps that has to do with the old firmware of the TFT. the blueprint by the way is the Version: v.3.4

**Comment by edwardtfn** [comment]
Is this the first time you are uploading a TFT file to this panel?

**Comment by lennartschulte** [comment]
1. No it's not. It's in relation to my other ticket I opened because the buttons on the TFT stopped working. Most likely due to the old firmware of the TFT
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/912 that's the reason I try to update it. When I click on "Exit parse" nothing happens and I just get the message in the log that a variable in nextion is missing.
2. Yes. All 3 URLs in the log work in the browser to download the file directly

**Comment by edwardtfn** [comment]
We have the same Nextion version, but looks like you are running an older firmware (69) than mine (72).

```log
[01:20:03][C][nextion:117]: Nextion:
[01:20:03][C][nextion:118]:   Device Model:     NX4832F035_011C
[01:20:03][C][nextion:119]:   Firmware Version: 72
[01:20:03][C][nextion:120]:   Serial Number:    01663401C1355267
[01:20:03][C][nextion:121]:   Flash Size:       16777216
[01:20:03][C][nextion:122]:   Wake On Touch:    True
```

**Comment by lennartschulte** [comment]
Can I update this somehow? I thought that's what I try to update with the "Update TFT" my goal is to get my panel working and responding again. It worked for several months but I just recently recognized that the buttons (touch) did not work and therefore wanted to update all to latest version to check if I get it working again as I did in the past

**Comment by deejaybeam** [comment]
To be honest: I don´t know how to update the internal nextion firmware version. This has nothing to do with our project/file-versions. Maybe this is included in the compiled tft belonging to the nextion-editor-version used to compile the tft from hmi.

The exit-reparse-button is only required to change the operation-mode of an virgin device that is flashed the first time.
After successful installation/flash of any tft from this project it is not required anymore.

Ignore the message "Nextion reported variable name invalid!" this is only because esphome tries to read something that does not exist in the installed tft - mainly caused because of different versions between esphome and tft.

You could try to install the current blank.tft, but your problem is, that any url you try is rejected.
This can be caused by the configuration of you HA itself, but you could try to use any other internal web-server that can serve files via http - not https and may depend to your nextion-firmware.
Another short and easy try would be to remame the tft-file from "nspanel_eu.tft" to "nspaneleu.tft".
It was reported that some user had this issue (maybe depends to nextion FW?)

**Comment by lennartschulte** [comment]
I just downloaded the TFT file fresh, changed the location and the name in one go. With the next try, I was able to perform the update. That's great, although I'm not sure what helped in the end. The TFT is currently updating. Let's hope all works as it's supposed to afterwards.

**Comment by lennartschulte** [comment]
all works like a charm. Many thanks for all the help!!
@edwardtfn also many thanks for the help in the other issue.

**Comment by deejaybeam** [comment]
Great to hear!
What nextion version do you now see in the esphome logs?

**Comment by lennartschulte** [comment]
It's now 72 so obviously it's the TFT update which sets the version.
