### ISSUE TITLE
Touch not working after a few days

### ISSUE THREAD

**Issue by Ralms** [Blackymas/NSPanel_HA_Blueprint#972]
Hi there,

I've been running 2 NSPanels with HA Blueprint for around 2 weeks now and one of them a couple days ago, just stopped responding to touch inputs. 

Everything else works, buttons work, it connects to Home Assistant to get the Blueprint, etc.
I've also did the "Update TFT" again, however no change, touch continues to be unresponsive. 

As such, I have a couple questions:
1. What is the best way to troubleshoot this to understand if the unit is defective or some software issue? 
2. Is there any information or process on how to revert everything (ESP32 and Nextion panel) to factory specs, so I can return the unit under warranty? (I still have a third unused unit) 

Thank you

**Comment by edwardtfn** [comment]
> What is the best way to troubleshoot this to understand if the unit is defective or some software issue?

1. Open ESPHome logs and you will be able to see live when you touch any place on the screen, as almost any touch will be reported in the log.
2. The entity `nspanel_event' is updated every ime a component in the display is pressed or released, so it's probably the best place to look on Home Assistant. That variable is used by the Blueprint.
3. If nothing in the logs, then I would open the device and look for some loseness in the cables/connectors.

> Is there any information or process on how to revert everything (ESP32 and Nextion panel) to factory specs, so I can return the unit under warranty? (I still have a third unused unit)

I'm pretty sure I have the files you will need (ESP32 firmware and TFT) somewhere here, but will have to look.
Please let me know the results from the tests above and if the problem is really on your hardware I can look for those files (with no commitment 😉).

**Comment by edwardtfn** [comment]
I will take a look later on how to revert to Sonoff.
It's good to hear your panel is back to life

**Comment by Ralms** [comment]
> I will take a look later on how to revert to Sonoff. It's good to hear your panel is back to life

I take it back, its really defective, not working again from one day to another and I haven't even touched it after fixing it yesterday. 
I think I will really need to RMA this one.

**Comment by edwardtfn** [comment]
That is sad. :(

So, I've googled and played a bit with this thing about reverting to stock firmware and I think I've succeeded with these steps:

1. Download the stock TFT file from [this link](https://github.com/masto/NSPanel-Demo-Files/issues/4#issuecomment-1034608391) and then upload it to your local server.
2. Use the service esphome.xxxxx_upload_tft_url to upload that TFT to your panel.
3. Download the stock firmware from [this link](https://community.jeedom.com/t/recherche-firmware-dorigine-nspanel/99561/3). You will have to rename the file from `.bin.txt` to `.bin`.
4. Flash this file to your panel. In my case, it haven't worked with OTA, so I had disassembled my panel and flashed thru serial using the [ESPHome flashing page](https://web.esphome.io/).
5. That's it! Now you should be able to pair with eWeLink app using Bluetooth pairing.
